# Generated by Django 2.2 on 2020-05-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ueser',
            new_name='user',
        ),
    ]
